name: dhrigro
description: Dhrigro - Everything Your Kitchen Needs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # Networking
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # UI
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_animate: ^4.5.2

  # Utils
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1

  # Firebase (notifications)
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

  # Payments
  razorpay_flutter: ^1.4.0

  # Upload
  image_picker: ^1.1.2
  file_picker: ^8.3.7
  excel: ^4.0.6
  mime: ^2.0.0
  fl_chart: ^0.70.2
  socket_io_client: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.4
  json_serializable: ^6.9.4
  freezed: ^2.5.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - .env.development
