-- AlterEnum: add admin roles
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'OPERATIONS_ADMIN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'INVENTORY_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CUSTOMER_SUPPORT';
